import { stat } from 'node:fs/promises';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { ensureMcpKey, mcpKeyPath } from './mcpKey.js';

describe('ensureMcpKey', () => {
  let vaultRoot: string;

  beforeEach(async () => {
    vaultRoot = await mkdtemp(join(tmpdir(), 'sidetrack-mcpkey-'));
  });

  afterEach(async () => {
    await rm(vaultRoot, { recursive: true, force: true });
  });

  it('generates a key when none exists (created=true)', async () => {
    const result = await ensureMcpKey(vaultRoot);

    expect(result.created).toBe(true);
    expect(result.key.length).toBeGreaterThan(0);
    expect(result.path).toBe(mcpKeyPath(vaultRoot));
  });

  it('writes to _BAC/.config/mcp.key with mode 0o600', async () => {
    await ensureMcpKey(vaultRoot);

    const keyFile = mcpKeyPath(vaultRoot);
    const info = await stat(keyFile);
    // Mode bits: 0o600 = user read+write only.
    // eslint-disable-next-line no-bitwise
    expect(info.mode & 0o777).toBe(0o600);
  });

  it('returns the same key on subsequent calls (stable across boots)', async () => {
    const first = await ensureMcpKey(vaultRoot);
    const second = await ensureMcpKey(vaultRoot);

    expect(second.key).toBe(first.key);
    expect(second.created).toBe(false);
    expect(second.path).toBe(first.path);
  });

  it('persisted key matches the file contents', async () => {
    const result = await ensureMcpKey(vaultRoot);
    const onDisk = (await readFile(result.path, 'utf8')).trim();

    expect(onDisk).toBe(result.key);
  });

  it('generated key differs from a separately generated bridge key (distinct key spaces)', async () => {
    const { ensureBridgeKey } = await import('./bridgeKey.js');
    const bridgeResult = await ensureBridgeKey(vaultRoot);
    const mcpResult = await ensureMcpKey(vaultRoot);

    // Structurally different paths.
    expect(mcpResult.path).not.toBe(bridgeResult.path);
    // Cryptographically distinct values (astronomically unlikely to collide).
    expect(mcpResult.key).not.toBe(bridgeResult.key);
  });
});

describe('F02 companion config wires mcpBridgeKey', () => {
  // Verify that a request authenticated with the mcp key is classified
  // as an MCP caller ('mcp') and one with the bridge key is 'extension'.
  // This mirrors the mcpTrustAndExport.test.ts pattern but focuses on
  // the KEY ORIGIN — the mcp.key generated by ensureMcpKey.

  let vaultRoot: string;

  beforeEach(async () => {
    vaultRoot = await mkdtemp(join(tmpdir(), 'sidetrack-mcpkey-classify-'));
  });

  afterEach(async () => {
    await rm(vaultRoot, { recursive: true, force: true });
  });

  it('request using mcp key classifies as mcp; bridge key classifies as extension', async () => {
    const { ensureBridgeKey } = await import('./bridgeKey.js');
    const { createVaultWriter } = await import('../vault/writer.js');
    const { createIdempotencyStore } = await import('../http/idempotency.js');
    const { handleRequest } = await import('../http/server.js');
    const { Readable } = await import('node:stream');

    const bridgeResult = await ensureBridgeKey(vaultRoot);
    const mcpResult = await ensureMcpKey(vaultRoot);

    // The two keys must be different — this is the invariant F02 relies on.
    expect(mcpResult.key).not.toBe(bridgeResult.key);

    type Config = import('../http/server.js').CompanionHttpConfig;
    const context: Config = {
      bridgeKey: bridgeResult.key,
      mcpBridgeKey: mcpResult.key,
      vaultWriter: createVaultWriter(vaultRoot),
      vaultRoot,
      idempotencyStore: createIdempotencyStore(vaultRoot),
    };

    // A read-only route that echoes back the caller class via the
    // /v1/status route (which doesn't exist in the minimal test server,
    // so use /v1/workstreams GET which is a real route).
    const makeRequest = async (key: string): Promise<number> => {
      const req = new Readable({
        read() {
          this.push(null);
        },
      }) as unknown as import('node:http').IncomingMessage;
      const headers: Record<string, string> = {
        host: '127.0.0.1',
        'x-bac-bridge-key': key,
      };
      Object.assign(req, {
        method: 'GET',
        url: '/v1/workstreams',
        headers,
      });
      let statusCode = 0;
      const res = {
        statusCode: 200,
        writeHead(code: number) {
          statusCode = code;
          return this;
        },
        write() {
          return true;
        },
        end() {},
      } as unknown as import('node:http').ServerResponse;
      await handleRequest(req, res, context);
      return statusCode;
    };

    // Both keys must be accepted (200 OK, not 401).
    const withMcpKey = await makeRequest(mcpResult.key);
    const withBridgeKey = await makeRequest(bridgeResult.key);

    expect(withMcpKey).not.toBe(401);
    expect(withBridgeKey).not.toBe(401);

    // A wrong key must be rejected.
    const withWrongKey = await makeRequest('totally-wrong-key');
    expect(withWrongKey).toBe(401);
  });
});
