import { describe, expect, it } from 'vitest';

import * as companion from './localLlmChild.entry.js';
// Import the extension's synthesis module DIRECTLY via a relative path so the
// parity assertions compare against the REAL source, not a hand-copied string.
// The extension file only depends on '../../graph/fnv1a' (a pure hash util),
// so a bun-test relative import resolves cleanly across the monorepo. If a
// future extension refactor makes this import unclean, replace the imports
// below with inline string literals and downgrade this to a textual snapshot
// (noting the parity is then textual, not live).
import * as extension from '../../../sidetrack-extension/src/sidepanel/nano/titleSynthesis.js';

// PARITY: the companion's local-LLM title synthesis MUST use the same prompt
// text and the same slice shape as the panel's Gemini-Nano path, so a title
// generated by either producer reads the same. These assertions are the guard
// against the two drifting — change one, this test fails until the other
// matches.
describe('local-llm parity with the extension title-synthesis path', () => {
  it('prompt prefix is identical', () => {
    expect(companion.TITLE_PROMPT_PREFIX).toBe(extension.TITLE_PROMPT_PREFIX);
  });

  it('thin-content + max-title thresholds are identical', () => {
    expect(companion.MIN_CONTENT_CHARS).toBe(extension.MIN_CONTENT_CHARS);
    expect(companion.MAX_TITLE_CHARS).toBe(extension.MAX_TITLE_CHARS);
    expect(companion.SLICE_THRESHOLD_CHARS).toBe(extension.SLICE_THRESHOLD_CHARS);
  });

  it('slice output is identical for short (pass-through) and long (head+middle+tail) content', () => {
    const short = 'A short conversation that is under the slice threshold.';
    expect(companion.sliceForSynthesis(short)).toBe(extension.sliceForSynthesis(short));
    expect(companion.sliceForSynthesis(short)).toBe(short);

    // Long content > SLICE_THRESHOLD_CHARS: exercise the head+middle+tail path.
    const long = Array.from({ length: 5000 }, (_v, i) => String.fromCharCode(97 + (i % 26))).join('');
    expect(long.length).toBeGreaterThan(companion.SLICE_THRESHOLD_CHARS);
    expect(companion.sliceForSynthesis(long)).toBe(extension.sliceForSynthesis(long));
    // The sliced form is strictly shorter than the input (sampling happened).
    expect(companion.sliceForSynthesis(long).length).toBeLessThan(long.length);
  });
});
