import type { ReactElement } from 'react';

import { FeedbackButtons, type FeedbackChoice } from '../feedback/FeedbackButtons';
import { ProducerPin } from './ProducerPin';
import type { ConnectionEdgeProducedBy } from './types';
import { reasonConfidence, type Reason } from './why-related/reasons';
import { renderReason } from './why-related/render';
import { sortReasons } from './why-related/sort';

export interface WhyRelatedFeedback {
  readonly label?: string;
  readonly onFeedback: (choice: FeedbackChoice) => Promise<void> | void;
}

export interface WhyRelatedPanelProps {
  readonly fromVisitId: string;
  readonly toVisitId?: string;
  readonly toTopicId?: string;
  readonly reasons: readonly Reason[];
  readonly showOnlyUserAsserted: boolean;
  readonly feedback?: WhyRelatedFeedback;
  // S27 — when this edge was generated by a versioned producer (ranker /
  // visit-similarity / topic-clusterer / engagement-classifier /
  // continuation-classifier / snippet-lineage), surface the ProducerPin so
  // the user can pin a specific revision and the system surfaces that
  // revision's outputs going forward.
  readonly producedBy?: ConnectionEdgeProducedBy;
  readonly producerLabel?: string;
  readonly trainedFromCorrectionCount?: number;
  readonly onToggleAssertedOnly: () => void;
  readonly onClose: () => void;
}

export const WhyRelatedPanel = ({
  fromVisitId,
  toVisitId,
  toTopicId,
  reasons,
  showOnlyUserAsserted,
  feedback,
  producedBy,
  producerLabel,
  trainedFromCorrectionCount,
  onToggleAssertedOnly,
  onClose,
}: WhyRelatedPanelProps): ReactElement => {
  const visibleReasons = sortReasons(reasons).filter(
    (reason) => !showOnlyUserAsserted || reasonConfidence(reason) === 'asserted',
  );
  return (
    <aside className="cx-why" data-testid="why-related-panel">
      <div className="cx-why-head">
        <div>
          <h4>Why related</h4>
          <p className="cx-mono cx-dim">
            {fromVisitId}
            {toVisitId === undefined ? '' : ` -> ${toVisitId}`}
            {toTopicId === undefined ? '' : ` -> ${toTopicId}`}
          </p>
        </div>
        <button type="button" className="cx-icon-button" onClick={onClose} aria-label="Close">
          ×
        </button>
      </div>
      <button
        type="button"
        className="cx-why-toggle"
        aria-pressed={showOnlyUserAsserted}
        onClick={onToggleAssertedOnly}
        data-testid="why-related-toggle"
      >
        Show only user-asserted
      </button>
      {feedback === undefined ? null : (
        <FeedbackButtons
          label={feedback.label ?? 'relation'}
          onFeedback={async (choice) => {
            await feedback.onFeedback(choice);
            return { ok: true };
          }}
        />
      )}
      {producedBy === undefined ? null : (
        <ProducerPin
          producedBy={producedBy}
          producerLabel={producerLabel}
          trainedFromCorrectionCount={trainedFromCorrectionCount}
        />
      )}
      <ul className="cx-why-list">
        {visibleReasons.map((reason) => (
          <li key={JSON.stringify(reason)} data-testid={`why-reason-${reason.code}`}>
            {renderReason(reason)}
          </li>
        ))}
      </ul>
    </aside>
  );
};
